"""add settings table

Revision ID: a2f8c0b5a32f
Revises: d3529d249dd9
Create Date: 2025-06-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a2f8c0b5a32f'
down_revision: Union[str, None] = 'd3529d249dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create settings table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'CONSTRUCTION_SETTINGS',
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('value', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: drop settings table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CONSTRUCTION_SETTINGS')
    # ### end Alembic commands ###